services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: NODE_VERSION
        value: "16"
