services:
  - type: web
    name: linestring-flask-app
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
    buildCommand: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: sh start.sh
